# Re-export ICON_PATHS for backward compatibility
from core.icons import ICON_PATHS

# ── Uygulama Sürümü ──────────────────────────────────────────────────────────
APP_VERSION = "1.1.7"

# ── YDL format sabitler ──────────────────────────────────────────────────────
# Bu string hem app.py hem downloader.py tarafından kullanılır.
# Tek yerden değiştirmek yeterlidir.
YDL_FORMAT = "bestaudio/bestaudio*/best"

# Theme colors
THEMES = {
    "Yeşil": {"accent": "#1DB954", "accent_hover": "#1ed760", "glow": "rgba(29, 185, 84, 0.4)"},
    "Mavi": {"accent": "#2D88FF", "accent_hover": "#4b9aff", "glow": "rgba(45, 136, 255, 0.4)"},
    "Mor": {"accent": "#B052F1", "accent_hover": "#bf6df5", "glow": "rgba(176, 82, 241, 0.4)"},
    "Kırmızı": {"accent": "#E91E63", "accent_hover": "#f06292", "glow": "rgba(233, 30, 99, 0.4)"},
    "Turuncu": {"accent": "#FF9800", "accent_hover": "#ffb74d", "glow": "rgba(255, 152, 0, 0.4)"},
}
CURRENT_THEME = "Yeşil"

BG_BLACK = "#070B12"
BG_DARK = "#0D1320"
BG_CARD = "#111827"
BG_CARD_HOVER = "#182235"
BG_ELEVATED = "#0E1626"
BORDER_COLOR = "#161f2e"
TEXT_PRIMARY = "#FFFFFF"
TEXT_SECONDARY = "#BAC6DA"
TEXT_MUTED = "#7D8CA5"
FONT_MAIN = "Segoe UI Variable Text"

# Home/search feed configuration
DYNAMIC_CONTENT = {
    "morning": [
        ("Güne Başla", "feed:tr.energetic"),
        ("Kahve & Akustik", "feed:tr.acoustic"),
        ("Enerjik Sabah", "feed:tr.pop"),
        ("Pazar Kahvaltısı", "feed:tr.classic.pop"),
    ],
    "noon": [
        ("Çalışma Modu", "feed:focus"),
        ("Motivasyon", "feed:tr.energetic"),
        ("Öğle Arası", "feed:tr.pop"),
        ("Global Pop Hit", "feed:global.pop"),
    ],
    "evening": [
        ("Eve Dönüş", "feed:tr.slow"),
        ("Gün Batımı", "feed:tr.rock"),
        ("Akşam Yemeği", "feed:tr.sanat"),
        ("Arkadaşlarla", "feed:tr.pop"),
    ],
    "night": [
        ("Uyku Modu", "feed:tr.slow"),
        ("Arabesk Damar", "feed:tr.arabesk"),
        ("Deep Thoughts", "feed:tr.rap"),
        ("Gece Sürüşü", "feed:tr.night"),
    ],
    "general": [
        ("Anadolu Rock", "feed:tr.anadolu.rock"),
        ("Türk Sanat", "feed:tr.sanat"),
        ("Türkçe Rap", "feed:tr.rap"),
        ("Global Top 50", "feed:charts.global"),
        ("Türkiye Top 50", "feed:charts.tr"),
        ("Pop Seçkisi", "feed:tr.pop"),
        ("90'lar Türkçe", "feed:tr.classic.pop"),
        ("Kral Pop", "feed:tr.pop"),
    ],
}

TRENDING_SECTIONS = [
    ("Trend Olanlar", "feed:charts.tr"),
    ("Yeni Çıkanlar", "feed:new.music"),
    ("Pop Hitleri", "feed:tr.pop"),
    ("Rap Hitleri", "feed:tr.rap"),
    ("Rock Hitleri", "feed:tr.rock"),
    ("Slow Şarkılar", "feed:tr.slow"),
    ("Global Hitleri", "feed:charts.global"),
    ("Bu Hafta Top 20", "feed:charts.tr"),
    ("Bu Ay Öne Çıkanlar", "feed:charts.global"),
]

TRENDING_QUERIES = [query for _, query in TRENDING_SECTIONS]

CATEGORY_BUTTONS = [
    ("Trendler", "feed:charts.tr", "songs"),
    ("Yeni Çıkanlar", "feed:new.music", "songs"),
    ("Türkçe Rap", "feed:tr.rap", "songs"),
    ("Türkçe Pop", "feed:tr.pop", "songs"),
    ("Slow", "feed:tr.slow", "songs"),
    ("Eski Türkçe", "feed:tr.classic.pop", "songs"),
    ("Global", "feed:charts.global", "songs"),
    ("Arabesk", "feed:tr.arabesk", "songs"),
]

SMART_FEEDS = {
    "feed:charts.tr": {
        "kind": "charts",
        "country": "TR",
        "gl": "TR",
        "hl": "tr",
        "max_sources": 4,
        "fallback_queries": [
            "turkce viral songs official audio",
            "turkce hit sarkilar official audio",
            "trend turkce sarkilar official audio",
            "turkce populer sarkilar official audio",
        ],
        "prefer_turkish": True,
        "recent_years": 2,
        "max_age_years": 4,
        "title_reject_tokens": ["new music friday", "top 20", "top 50", "spotify", "viral hits", "biggest hits", "new year"],
        "avoid_tokens": ["remix", "sped up", "slowed", "karaoke", "cover", "lyrics"],
    },
    "feed:charts.global": {
        "kind": "charts",
        "country": "US",
        "gl": "US",
        "hl": "en",
        "max_sources": 4,
        "fallback_queries": [
            "global chart songs official audio",
            "viral global songs official audio",
            "worldwide hit songs official audio",
            "global pop hits official audio",
        ],
        "prefer_turkish": False,
        "recent_years": 2,
        "max_age_years": 4,
        "title_reject_tokens": ["new music friday", "top 20", "top 50", "spotify", "viral hits", "biggest hits", "new year"],
        "avoid_tokens": ["remix", "sped up", "slowed", "karaoke", "cover", "lyrics"],
    },
    "feed:new.music": {
        "kind": "search",
        "gl": "TR",
        "hl": "tr",
        "max_sources": 4,
        "queries": [
            "bu hafta cikan turkce sarkilar official audio",
            "yeni cikan turkce sarkilar official audio",
            "trend turkce yeni sarkilar official audio",
            "yeni populer turkce sarkilar official audio",
            "fresh turkish music official audio",
        ],
        "search_limit": 18,
        "prefer_turkish": True,
        "prefer_tokens": [],
        "strict_recent": True,
        "recent_years": 1,
        "max_age_years": 2,
        "title_reject_tokens": ["new music friday", "top 20", "top 50", "spotify", "viral hits", "biggest hits", "playlist", "new year"],
        "avoid_tokens": ["sped up", "slowed", "karaoke", "cover", "lyrics"],
    },
    "feed:tr.pop": {
        "kind": "search",
        "gl": "TR",
        "hl": "tr",
        "max_sources": 4,
        "queries": [
            "simge edis mabel matiz hadise zeynep bastik melike sahin pop",
            "turkce pop yeni sarkilar official audio",
            "turkce pop viral hitler",
            "turkce pop populer sarkilar",
            "turkce pop hitleri official audio",
            "turkce pop official audio",
        ],
        "search_limit": 18,
        "prefer_turkish": True,
        "prefer_tokens": ["pop", "hit", "viral"],
        "recent_years": 2,
        "max_age_years": 4,
        "title_reject_tokens": ["new music friday", "top 20", "top 50", "spotify", "playlist", "new year"],
        "artist_boost_tokens": [
            "simge", "edis", "mabel matiz", "hadise", "hande yener",
            "zeynep bastik", "melike sahin", "buray", "mustafa sandal",
            "irem derici", "demet akalin", "gokhan turkmen", "yalin",
        ],
        "hard_reject_tokens": ["drill", "trap", "freestyle", "diss", "arabesk damar", "turk sanat"],
        "avoid_tokens": ["remix", "sped up", "slowed", "karaoke", "cover"],
    },
    "feed:tr.rap": {
        "kind": "search",
        "gl": "TR",
        "hl": "tr",
        "max_sources": 4,
        "queries": [
            "uzi motive blok3 cakal reckol lvbel5 heijan wegh rap",
            "turkce rap yeni sarkilar official audio",
            "turkce drill official audio",
            "turkce trap official audio",
            "turkce melodik rap official audio",
            "turkce rap official audio",
        ],
        "search_limit": 18,
        "prefer_turkish": True,
        "strict_profile": True,
        "prefer_tokens": ["rap", "drill", "trap", "hip hop", "hiphop", "freestyle"],
        "recent_years": 2,
        "max_age_years": 4,
        "title_reject_tokens": ["new music friday", "top 20", "top 50", "spotify", "playlist", "new year"],
        "required_any_tokens": [
            "rap", "drill", "trap", "hip hop", "hiphop", "freestyle", "diss",
            "uzi", "motive", "blok3", "blok 3", "cakal", "reckol", "ceza",
            "ezhel", "gazapizm", "norm ender", "lvbel", "batuflex",
            "khontkar", "heijan", "wegh", "cash flow", "joker", "tepki",
            "eypio", "massaka", "fero", "maestro", "stabil",
        ],
        "artist_boost_tokens": [
            "uzi", "motive", "blok3", "blok 3", "cakal", "reckol", "ceza",
            "ezhel", "gazapizm", "norm ender", "lvbel", "batuflex",
            "khontkar", "heijan", "wegh", "cash flow", "joker", "tepki",
            "eypio", "massaka", "fero", "maestro", "stabil",
        ],
        "hard_reject_tokens": [
            "akustik", "arabesk", "damar", "turk sanat", "sanat muzigi",
            "ilah", "unplugged", "slow version", "mixify", "type beat", "beatz",
        ],
        "avoid_tokens": ["remix", "sped up", "slowed", "karaoke", "cover"],
    },
    "feed:tr.rock": {
        "kind": "search",
        "gl": "TR",
        "hl": "tr",
        "max_sources": 3,
        "queries": [
            "alternatif turkce rock {year}",
            "turkce rock {year}",
            "turkce rock yeni sarkilar",
            "turkce rock populer sarkilar",
        ],
        "search_limit": 16,
        "prefer_turkish": True,
        "prefer_tokens": ["rock"],
        "artist_boost_tokens": [
            "duman", "mor ve otesi", "manga", "gripin", "seksendort",
            "yuksek sadakat", "teoman", "athena", "pinhani",
        ],
        "hard_reject_tokens": ["drill", "trap", "arabesk damar", "turk sanat"],
        "avoid_tokens": ["live", "cover", "remix"],
    },
    "feed:tr.slow": {
        "kind": "search",
        "gl": "TR",
        "hl": "tr",
        "max_sources": 4,
        "queries": [
            "turkce slow {year}",
            "duygusal turkce sarkilar {year}",
            "turkce slow yeni sarkilar",
            "gece icin turkce slow",
            "romantik turkce sarkilar {year}",
        ],
        "search_limit": 16,
        "prefer_turkish": True,
        "prefer_tokens": ["slow", "akustik", "duygusal"],
        "avoid_tokens": ["sped up", "slowed", "karaoke", "cover"],
    },
    "feed:tr.acoustic": {
        "kind": "search",
        "gl": "TR",
        "hl": "tr",
        "max_sources": 3,
        "queries": [
            "turkce akustik {year}",
            "turkce akustik pop {year}",
            "akustik turkce sarkilar",
            "turkce unplugged",
        ],
        "search_limit": 16,
        "prefer_turkish": True,
        "prefer_tokens": ["akustik", "acoustic"],
        "avoid_tokens": ["cover", "karaoke"],
    },
    "feed:tr.energetic": {
        "kind": "search",
        "gl": "TR",
        "hl": "tr",
        "max_sources": 4,
        "queries": [
            "hareketli turkce pop {year}",
            "turkce enerji sarkilari {year}",
            "turkce motivasyon sarkilari",
            "turkce party hitleri {year}",
            "turkce hizli sarkilar {year}",
        ],
        "search_limit": 16,
        "prefer_turkish": True,
        "prefer_tokens": ["pop", "enerji", "motivasyon"],
        "avoid_tokens": ["karaoke", "cover", "remix"],
    },
    "feed:tr.morning.pop": {
        "kind": "search",
        "gl": "TR",
        "hl": "tr",
        "max_sources": 4,
        "queries": [
            "mutlu turkce pop official audio {year}",
            "enerjik turkce pop official audio {year}",
            "pozitif turkce pop sarkilar official audio",
            "turkce sabah pop hitleri {year}",
            "iyi hissettiren turkce pop sarkilar",
        ],
        "search_limit": 16,
        "prefer_turkish": True,
        "prefer_tokens": ["pop", "mutlu", "enerjik", "hareketli"],
        "hard_reject_tokens": ["drill", "trap", "arabesk", "damar", "slow version"],
        "avoid_tokens": ["karaoke", "cover", "remix", "sped up", "slowed"],
    },
    "feed:tr.morning.rap": {
        "kind": "search",
        "gl": "TR",
        "hl": "tr",
        "max_sources": 4,
        "queries": [
            "turkce melodik rap official audio {year}",
            "turkce enerjik rap official audio {year}",
            "turkce hype rap official audio {year}",
            "morning turkish rap official audio",
            "uzi motive blok3 cakal melodik rap",
        ],
        "search_limit": 18,
        "prefer_turkish": True,
        "strict_profile": True,
        "prefer_tokens": ["rap", "melodik", "enerjik", "trap", "hip hop"],
        "required_any_tokens": [
            "rap", "drill", "trap", "hip hop", "hiphop", "freestyle", "diss",
            "uzi", "motive", "blok3", "blok 3", "cakal", "reckol", "ceza",
            "ezhel", "gazapizm", "norm ender", "lvbel", "batuflex",
            "khontkar", "heijan", "wegh", "cash flow", "joker", "tepki",
            "eypio", "massaka", "fero", "maestro", "stabil",
        ],
        "artist_boost_tokens": [
            "uzi", "motive", "blok3", "blok 3", "cakal", "reckol", "ceza",
            "ezhel", "gazapizm", "norm ender", "lvbel", "batuflex",
            "khontkar", "heijan", "wegh", "cash flow", "joker", "tepki",
            "eypio", "massaka", "fero", "maestro", "stabil",
        ],
        "hard_reject_tokens": ["akustik", "arabesk", "damar", "turk sanat", "slow version"],
        "avoid_tokens": ["karaoke", "cover", "remix", "sped up", "slowed"],
    },
    "feed:tr.classic.pop": {
        "kind": "search",
        "gl": "TR",
        "hl": "tr",
        "max_sources": 3,
        "queries": [
            "90lar turkce pop",
            "eski turkce pop hitleri",
            "2000ler turkce pop",
            "nostalji turkce pop",
        ],
        "search_limit": 16,
        "prefer_turkish": True,
        "prefer_tokens": ["90", "pop"],
        "avoid_tokens": ["remix", "cover"],
    },
    "feed:tr.sanat": {
        "kind": "search",
        "gl": "TR",
        "hl": "tr",
        "max_sources": 3,
        "queries": [
            "turk sanat muzigi",
            "turk sanat muzigi klasik",
            "zeki muren klasikleri",
            "muazzez ersoy populer",
        ],
        "search_limit": 14,
        "prefer_turkish": True,
        "avoid_tokens": ["remix", "cover"],
    },
    "feed:tr.arabesk": {
        "kind": "search",
        "gl": "TR",
        "hl": "tr",
        "max_sources": 4,
        "queries": [
            "arabesk damar",
            "arabesk hitleri",
            "arabesk populer sarkilar",
            "damar turkce sarkilar",
            "arabesk {year}",
        ],
        "search_limit": 14,
        "prefer_turkish": True,
        "strict_profile": True,
        "prefer_tokens": ["arabesk"],
        "required_any_tokens": [
            "arabesk", "damar", "muslum gurses", "ferdi tayfur",
            "orhan gencebay", "ibrahim tatlises", "bergen", "emrah",
        ],
        "artist_boost_tokens": [
            "muslum gurses", "ferdi tayfur", "orhan gencebay",
            "ibrahim tatlises", "bergen", "emrah",
        ],
        "hard_reject_tokens": ["drill", "trap", "rock", "akustik", "edm"],
        "avoid_tokens": ["remix", "cover"],
    },
    "feed:tr.anadolu.rock": {
        "kind": "search",
        "gl": "TR",
        "hl": "tr",
        "max_sources": 3,
        "queries": [
            "anadolu rock",
            "turk rock klasik",
            "anadolu rock efsaneleri",
            "baris manco cem karaca erkin koray",
        ],
        "search_limit": 14,
        "prefer_turkish": True,
        "prefer_tokens": ["rock"],
        "avoid_tokens": ["cover", "live remix"],
    },
    "feed:tr.night": {
        "kind": "search",
        "gl": "TR",
        "hl": "tr",
        "max_sources": 4,
        "queries": [
            "gece yolculugu sarkilari",
            "gece sarkilari turkce {year}",
            "turkce night drive",
            "turkce slow gece",
            "late night turkish songs",
        ],
        "search_limit": 16,
        "prefer_turkish": True,
        "prefer_tokens": ["gece", "night", "slow"],
        "avoid_tokens": ["karaoke", "cover", "remix"],
    },
    "feed:tr.evening.pop": {
        "kind": "search",
        "gl": "TR",
        "hl": "tr",
        "max_sources": 4,
        "queries": [
            "sakin turkce pop official audio {year}",
            "turkce chill pop official audio {year}",
            "turkce akustik pop gece",
            "aksam icin turkce pop sarkilar",
            "soft turkce pop songs",
        ],
        "search_limit": 16,
        "prefer_turkish": True,
        "prefer_tokens": ["slow", "akustik", "chill", "pop", "gece"],
        "hard_reject_tokens": ["drill", "trap", "freestyle", "arabesk damar"],
        "avoid_tokens": ["karaoke", "cover", "remix", "sped up", "slowed"],
    },
    "feed:tr.evening.rap": {
        "kind": "search",
        "gl": "TR",
        "hl": "tr",
        "max_sources": 4,
        "queries": [
            "turkce melodik rap gece official audio {year}",
            "turkce chill rap official audio {year}",
            "turkce gece rap official audio {year}",
            "turkce duygusal rap official audio {year}",
            "late night turkish rap official audio",
        ],
        "search_limit": 18,
        "prefer_turkish": True,
        "strict_profile": True,
        "prefer_tokens": ["rap", "melodik", "chill", "gece", "night"],
        "required_any_tokens": [
            "rap", "drill", "trap", "hip hop", "hiphop", "freestyle", "diss",
            "uzi", "motive", "blok3", "blok 3", "cakal", "reckol", "ceza",
            "ezhel", "gazapizm", "norm ender", "lvbel", "batuflex",
            "khontkar", "heijan", "wegh", "cash flow", "joker", "tepki",
            "eypio", "massaka", "fero", "maestro", "stabil",
        ],
        "artist_boost_tokens": [
            "uzi", "motive", "blok3", "blok 3", "cakal", "reckol", "ceza",
            "ezhel", "gazapizm", "norm ender", "lvbel", "batuflex",
            "khontkar", "heijan", "wegh", "cash flow", "joker", "tepki",
            "eypio", "massaka", "fero", "maestro", "stabil",
        ],
        "hard_reject_tokens": ["akustik", "arabesk", "damar", "turk sanat", "diss track"],
        "avoid_tokens": ["karaoke", "cover", "remix", "sped up", "slowed"],
    },
    "feed:global.pop": {
        "kind": "search",
        "gl": "US",
        "hl": "en",
        "max_sources": 4,
        "queries": [
            "global pop hits {year}",
            "todays top hits songs {year}",
            "viral pop songs {year}",
            "top pop songs worldwide {year}",
            "new pop hits {year}",
        ],
        "search_limit": 18,
        "prefer_turkish": False,
        "prefer_tokens": ["pop", "hit"],
        "artist_boost_tokens": [
            "taylor swift", "sabrina carpenter", "dua lipa", "billie eilish",
            "ariana grande", "olivia rodrigo", "the weeknd", "doja cat",
        ],
        "hard_reject_tokens": ["drill", "freestyle", "phonk"],
        "avoid_tokens": ["remix", "sped up", "slowed", "karaoke", "cover"],
    },
    "feed:global.morning.pop": {
        "kind": "search",
        "gl": "US",
        "hl": "en",
        "max_sources": 4,
        "queries": [
            "happy pop songs {year}",
            "feel good pop hits {year}",
            "morning pop songs {year}",
            "upbeat pop hits {year}",
            "sunny pop playlist songs",
        ],
        "search_limit": 18,
        "prefer_turkish": False,
        "prefer_tokens": ["pop", "happy", "upbeat", "feel good"],
        "artist_boost_tokens": [
            "taylor swift", "sabrina carpenter", "dua lipa", "billie eilish",
            "ariana grande", "olivia rodrigo", "the weeknd", "doja cat",
        ],
        "hard_reject_tokens": ["drill", "freestyle", "phonk"],
        "avoid_tokens": ["remix", "sped up", "slowed", "karaoke", "cover"],
    },
    "feed:global.rap": {
        "kind": "search",
        "gl": "US",
        "hl": "en",
        "max_sources": 4,
        "queries": [
            "global rap hits {year}",
            "hip hop hits songs {year}",
            "viral rap songs {year}",
            "new rap hits {year}",
            "trap hits {year}",
        ],
        "search_limit": 18,
        "prefer_turkish": False,
        "strict_profile": True,
        "prefer_tokens": ["rap", "hip hop", "trap"],
        "required_any_tokens": [
            "rap", "hip hop", "hiphop", "trap", "drill", "freestyle",
            "travis scott", "kendrick lamar", "drake", "future",
            "metro boomin", "21 savage", "lil baby", "playboi carti",
        ],
        "artist_boost_tokens": [
            "travis scott", "kendrick lamar", "drake", "future",
            "metro boomin", "21 savage", "lil baby", "playboi carti",
            "j cole", "asap rocky",
        ],
        "hard_reject_tokens": ["acoustic", "ballad", "karaoke", "piano version"],
        "avoid_tokens": ["remix", "sped up", "slowed", "karaoke", "cover"],
    },
    "feed:global.morning.rap": {
        "kind": "search",
        "gl": "US",
        "hl": "en",
        "max_sources": 4,
        "queries": [
            "upbeat rap songs {year}",
            "melodic rap hits {year}",
            "morning rap motivation songs",
            "feel good hip hop songs {year}",
            "hype rap playlist songs",
        ],
        "search_limit": 18,
        "prefer_turkish": False,
        "strict_profile": True,
        "prefer_tokens": ["rap", "hip hop", "melodic", "upbeat"],
        "required_any_tokens": [
            "rap", "hip hop", "hiphop", "trap", "drill", "freestyle",
            "travis scott", "kendrick lamar", "drake", "future",
            "metro boomin", "21 savage", "lil baby", "playboi carti",
        ],
        "artist_boost_tokens": [
            "travis scott", "kendrick lamar", "drake", "future",
            "metro boomin", "21 savage", "lil baby", "playboi carti",
            "j cole", "asap rocky",
        ],
        "hard_reject_tokens": ["acoustic", "ballad", "karaoke", "piano version"],
        "avoid_tokens": ["remix", "sped up", "slowed", "karaoke", "cover"],
    },
    "feed:global.evening.pop": {
        "kind": "search",
        "gl": "US",
        "hl": "en",
        "max_sources": 4,
        "queries": [
            "chill pop songs night",
            "soft pop songs {year}",
            "evening chill pop songs",
            "late night pop songs",
            "night drive pop songs",
        ],
        "search_limit": 18,
        "prefer_turkish": False,
        "prefer_tokens": ["chill", "soft", "pop", "night"],
        "artist_boost_tokens": [
            "billie eilish", "the weeknd", "dua lipa", "lany",
            "joji", "sza", "olivia rodrigo", "tate mcrae",
        ],
        "hard_reject_tokens": ["drill", "freestyle", "phonk"],
        "avoid_tokens": ["remix", "sped up", "slowed", "karaoke", "cover"],
    },
    "feed:global.evening.rap": {
        "kind": "search",
        "gl": "US",
        "hl": "en",
        "max_sources": 4,
        "queries": [
            "chill rap songs night",
            "late night melodic rap",
            "soft hip hop songs {year}",
            "night drive rap songs",
            "melodic late night rap {year}",
        ],
        "search_limit": 18,
        "prefer_turkish": False,
        "strict_profile": True,
        "prefer_tokens": ["rap", "hip hop", "chill", "melodic", "night"],
        "required_any_tokens": [
            "rap", "hip hop", "hiphop", "trap", "drill", "freestyle",
            "travis scott", "kendrick lamar", "drake", "future",
            "metro boomin", "21 savage", "lil baby", "playboi carti",
        ],
        "artist_boost_tokens": [
            "travis scott", "kendrick lamar", "drake", "future",
            "metro boomin", "21 savage", "lil baby", "playboi carti",
            "j cole", "asap rocky",
        ],
        "hard_reject_tokens": ["acoustic", "ballad", "karaoke", "piano version"],
        "avoid_tokens": ["remix", "sped up", "slowed", "karaoke", "cover"],
    },
    "feed:global.edm": {
        "kind": "search",
        "gl": "US",
        "hl": "en",
        "max_sources": 4,
        "queries": [
            "dance edm hits {year}",
            "electronic dance hits {year}",
            "festival edm {year}",
            "big room edm {year}",
            "viral dance songs {year}",
        ],
        "search_limit": 18,
        "prefer_turkish": False,
        "prefer_tokens": ["edm", "dance", "electronic"],
        "avoid_tokens": ["remix", "sped up", "slowed", "karaoke"],
    },
    "feed:chill": {
        "kind": "search",
        "gl": "US",
        "hl": "en",
        "max_sources": 4,
        "queries": [
            "chill acoustic songs",
            "lofi chill songs",
            "late night chill songs",
            "indie chill mix songs",
            "soft chill pop songs",
        ],
        "search_limit": 16,
        "prefer_tokens": ["chill", "lofi", "acoustic"],
        "avoid_tokens": ["remix", "sped up", "karaoke"],
    },
    "feed:focus": {
        "kind": "search",
        "gl": "US",
        "hl": "en",
        "max_sources": 3,
        "queries": [
            "focus songs",
            "study chill songs",
            "deep focus music songs",
            "work concentration songs",
        ],
        "search_limit": 14,
        "prefer_tokens": ["focus", "study", "chill"],
        "avoid_tokens": ["karaoke", "cover", "remix"],
    },
    "feed:tr.indie": {
        "kind": "search",
        "gl": "TR",
        "hl": "tr",
        "max_sources": 4,
        "queries": [
            "turkce indie pop",
            "turkce alternatif pop",
            "turkce indie {year}",
            "alternatif turkce sarkilar {year}",
            "turkce indie yeni sarkilar",
        ],
        "search_limit": 14,
        "prefer_turkish": True,
        "prefer_tokens": ["indie", "alternatif", "pop"],
        "avoid_tokens": ["karaoke", "cover", "remix"],
    },
}

SMART_FEED_ALIASES = {
    "Turkey Top 50 Songs": "feed:charts.tr",
    "Turkey Top 50": "feed:charts.tr",
    "Global Top 50 Songs": "feed:charts.global",
    "Global Top 50": "feed:charts.global",
    "Global Viral Hits 2026": "feed:charts.global",
    "New Music Daily Songs": "feed:new.music",
    "Turkce Pop Hits 2026": "feed:tr.pop",
    "Türkçe Pop Hits 2026": "feed:tr.pop",
    "Turkce Pop 2026": "feed:tr.pop",
    "Türkçe Pop 2026": "feed:tr.pop",
    "Turkce Rap Hits 2026": "feed:tr.rap",
    "Türkçe Rap Hits 2026": "feed:tr.rap",
    "Türkçe Rap Hits": "feed:tr.rap",
    "Alternatif Turkce Rock": "feed:tr.rock",
    "Alternatif Türkçe Rock": "feed:tr.rock",
    "Turkce Slow Hit": "feed:tr.slow",
    "Türkçe Slow Hit": "feed:tr.slow",
    "Türkçe Slow Şarkılar": "feed:tr.slow",
    "Sakin Türkçe": "feed:tr.slow",
    "Late Night Turkish Songs": "feed:tr.night",
    "Acoustic Chill Songs": "feed:chill",
    "Dance EDM Hits 2026": "feed:global.edm",
    "Dance EDM Electronic 2026": "feed:global.edm",
    "Arabesk Damar": "feed:tr.arabesk",
    "90lar Turkce Pop": "feed:tr.classic.pop",
    "90lar Türkçe Pop": "feed:tr.classic.pop",
    "Türkçe Akustik Pop": "feed:tr.acoustic",
    "Turkce Akustik Pop": "feed:tr.acoustic",
    "Türkçe Hareketli Pop": "feed:tr.energetic",
    "Turkce Hareketli Pop": "feed:tr.energetic",
    "Spor Türkçe Pop": "feed:tr.energetic",
    "Türkçe Enstrümantal": "feed:focus",
    "Turkce Enstrumantal": "feed:focus",
    "Türk Sanat Müziği": "feed:tr.sanat",
    "Turk Sanat Muzigi": "feed:tr.sanat",
    "Zeki Müren Klasikleri": "feed:tr.sanat",
    "Zeki Muren Klasikleri": "feed:tr.sanat",
    "Anadolu Rock Efsaneleri": "feed:tr.anadolu.rock",
    "Global Pop Hits": "feed:global.pop",
    "Morning Pop Hits": "feed:global.pop",
    "Focus Pop": "feed:global.pop",
    "Sunset Pop": "feed:global.pop",
    "Late Night Pop": "feed:global.pop",
    "Morning Rap Motivation": "feed:global.rap",
    "Focus Rap": "feed:global.rap",
    "Chill Rap": "feed:global.rap",
    "Late Night Rap": "feed:global.rap",
    "Melodic Rap Essentials": "feed:global.rap",
    "Turkce Melodik Rap": "feed:tr.rap",
    "Türkçe Melodik Rap": "feed:tr.rap",
    "Turkce Indie Pop": "feed:tr.indie",
    "Türkçe Indie Pop": "feed:tr.indie",
    "Indie Pop Essentials": "feed:tr.indie",
}

EQ_PRESETS = {
    "Düz": [0] * 10,
    "Bass": [6, 5, 4, 2, 0, 0, 0, 0, 0, 0],
    "Rock": [5, 4, 2, 0, -2, 0, 2, 4, 5, 5],
    "Pop": [-2, 0, 3, 5, 5, 3, 0, -2, -3, -3],
    "Jazz": [0, 0, 2, 4, 4, 3, 2, 0, -2, -2],
    "Klasik": [0, 0, 0, 0, 0, 0, -3, -5, -5, -6],
}
